### PR TITLE
Fix infinite recursive loop when zipping thousand files

### LINKED ISSUE #6: Infinite loop & 100% CPU utilization
PR #5 introduced an issue when we want to zip thousand files.

In fact, when the readed files count has reached the limit maxOpenFiles in addItem(), the addItem() function is called itself. And it is called recursively until some files have been read. But if reading files takes much more time than listing all files, we reach a point where there are too many infinite recursive loops for many files. Then it takes so many CPU resources that there are not enough CPU resources to read files. And the program never ends.

### PR DESCRIPTION
**Pull request by laurentj**
When there are too many files that are waiting to be read, there
are too many recursive loop for each files, and then it takes
so many CPU resources that other files cannot be readed (or very slowly).
So zipping directories containing thousand files may take several minutes
(or probably may never end).

Instead of doing a recursive loop to "wait" after an other file reading,
just let's use an async queue

Closes #6

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -77,20 +88,7 @@ function zipBuffer (rootDir, options, callback) {
...
-            }
-            folders[dir].file(file, data);
-            openFiles--;
-            cb(err);
-          });
-        }
-        else {
-          addItem(fullPath, cb);
-        }
+        fileQueue.push({fullPath: fullPath, dir:dir, file:file}, cb);
```
Comment (kumar303) [inline index.js]: this needs spaces between operators (like `dir: dir`)

**Comment by laurentj** [comment]
I fixed coding style ;-)

**Comment by kumar303** [comment]
@jsantell could you take a look? This adds proper queuing now.

File: index.js [hunk 2]
```diff
@@ -1,5 +1,7 @@
 var fs = require('fs');
 var path = require('path');
+var async = require('async');
```
Comment (jsantell) [inline index.js]: `var queue = require('async').queue;` because `async` is a keyword in ES7

File: index.js [hunk 3]
```diff
@@ -77,20 +88,7 @@ function zipBuffer (rootDir, options, callback) {
...
-            }
-            folders[dir].file(file, data);
-            openFiles--;
-            cb(err);
-          });
-        }
-        else {
-          addItem(fullPath, cb);
-        }
+        fileQueue.push({fullPath: fullPath, dir: dir, file: file}, cb);
```
Comment (jsantell) [inline index.js]: Spaces between object primitive's curlies: `{ fullPath: fullPath, dir: dir, file: file },`

**Comment by jsantell** [comment]
Some comments on styling -- with those changes, squashed commits, I'll merge this in and republish. Thank you!

**Comment by kumar303** [comment]
@laurentj thanks for all the follow-ups. Can you [squash this into one commit](https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request#squash-your-changes) ?

**Comment by laurentj** [comment]
Squash done :-)

**Comment by kumar303** [comment]
thanks!

**Comment by kumar303** [comment]
@jsantell are you able to cut a release for this soon? Thanks for the help.
